### ISSUE TITLE
Add support for style={{ borderRadius: x }}

### ISSUE THREAD

**Issue by fmacherey** [react-native-toolkit/triangle#5]
Hey guys,

I did find your lib yesterday and it's really nice and helpful. I use this to paint the tail / arrow of speech bubbles, as other solutions for react-native are more complicated (drawing the tail with a self generated SVG etc.).

Is there a way to have support for css-borderRadius attribute, to make the triangles look nicer? Or generally asked, is there a way to pass down `style` prop, and merge this with the internally setted prop?

Thanks for your answer and best wishes,
Florian

**Comment by DaniAkash** [comment]
The triangles are drawn using border colors of the views instead of using the view itself. It's a common CSS trick.

However if you need rounded triangle edges, I'd recommend using an SVG...

**Comment by fmacherey** [comment]
Thanks @DaniAkash for your quick response on this :)
